import { useEffect, useState } from 'react';
import {
    Box, Typography, Chip, Card, CardContent, CardActionArea,
    Collapse, Divider, Button, CircularProgress, Alert,
    Stack, IconButton, Tab, Tabs, Fade,
} from '@mui/material';
import {
    CheckCircleOutlined, EventOutlined, CancelOutlined,
    HourglassEmptyOutlined, LocalHospitalOutlined,
    MedicalServicesOutlined, ScienceOutlined, ExpandMoreOutlined,
    ExpandLessOutlined, AddOutlined, FiberManualRecord,
    AssignmentOutlined, MonitorHeartOutlined, ArrowBackOutlined,
    ReceiptOutlined, ContentPasteOutlined,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const API = 'http://localhost:8084';
const h   = (token) => ({ Authorization: `Bearer ${token}` });

const get = (url, token) => fetch(`${API}${url}`, { headers: h(token) }).then(r => r.json());

const STATUS = {
    COMPLETED:           { label: 'Completed',         color: '#4CAF50', bg: '#E8F5E9', Icon: CheckCircleOutlined },
    SCHEDULED:           { label: 'Scheduled',         color: '#1565C0', bg: '#E3F2FD', Icon: EventOutlined },
    IN_PROGRESS:         { label: 'In Progress',       color: '#E65100', bg: '#FFF3E0', Icon: HourglassEmptyOutlined },
    CANCELLED:           { label: 'Cancelled',         color: '#B71C1C', bg: '#FFEBEE', Icon: CancelOutlined },
    EMERGENCY_REDIRECT:  { label: 'Emergency',         color: '#B71C1C', bg: '#FFEBEE', Icon: LocalHospitalOutlined },
    DIAGNOSIS_PENDING:   { label: 'Diagnosis Pending', color: '#6A1B9A', bg: '#F3E5F5', Icon: MedicalServicesOutlined },
    FORM_COMPLETED:      { label: 'Form Completed',    color: '#00796B', bg: '#E0F2F1', Icon: AssignmentOutlined },
    FORM_GENERATED:      { label: 'Form Ready',        color: '#0277BD', bg: '#E1F5FE', Icon: AssignmentOutlined },
    PENDING_FORM:        { label: 'Pending Form',      color: '#827717', bg: '#F9FBE7', Icon: HourglassEmptyOutlined },
};

const COMPLEXITY = {
    SIMPLE:    { label: 'Simple',    color: '#2E7D32', bg: '#C8E6C9' },
    MEDIUM:    { label: 'Medium',    color: '#E65100', bg: '#FFE0B2' },
    COMPLEX:   { label: 'Complex',   color: '#4A148C', bg: '#E1BEE7' },
    EMERGENCY: { label: 'Emergency', color: '#B71C1C', bg: '#FFCDD2' },
};

const ALL_TABS = ['All', 'Completed', 'Active', 'Cancelled'];

function StatusChip({ status }) {
    const cfg = STATUS[status] || { label: status, color: '#8B7355', bg: '#F5F0E8', Icon: MonitorHeartOutlined };
    return (
        <Chip icon={<cfg.Icon sx={{ fontSize: '13px !important', color: `${cfg.color} !important` }} />}
              label={cfg.label} size="small"
              sx={{ bgcolor: cfg.bg, color: cfg.color, fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.68rem', border: `1px solid ${cfg.color}30` }} />
    );
}

/* ── Prescription/Referral mini cards ─────────────────────── */
function PrescriptionCard({ consultationId, token }) {
    const [data, setData]     = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        get(`/api/v1/prescriptions/consultation/${consultationId}`, token)
            .then(d => { setData(d); setLoading(false); })
            .catch(() => setLoading(false));
    }, [consultationId, token]);

    if (loading) return <CircularProgress size={16} sx={{ color: '#8B7355' }} />;
    if (!data) return null;

    const meds = data.medications || data.prescriptionMedications || [];
    return (
        <Box sx={{ mt: 1.5, p: 2, borderRadius: 2, bgcolor: '#E8F5E9', border: '1px solid #C8E6C9' }}>
            <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1 }}>
                <ReceiptOutlined sx={{ fontSize: 16, color: '#2E7D32' }} />
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.75rem', color: '#2E7D32', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                    Prescription #{data.id} {data.isAutoGenerated ? '· Auto' : '· Doctor issued'}
                </Typography>
            </Stack>
            {meds.slice(0, 3).map((m, i) => (
                <Stack key={i} direction="row" justifyContent="space-between" sx={{ py: 0.4 }}>
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.8rem', fontWeight: 600, color: '#1B5E20' }}>
                        {m.medicationName || m.medication_name}
                    </Typography>
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.75rem', color: '#388E3C' }}>
                        {m.dosage} · {m.frequency}
                    </Typography>
                </Stack>
            ))}
            {meds.length > 3 && <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.7rem', color: '#66BB6A', mt: 0.5 }}>+{meds.length - 3} more</Typography>}
        </Box>
    );
}

function ReferralCard({ consultationId, token }) {
    const [data, setData]     = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        get(`/api/referrals/consultation/${consultationId}`, token)
            .then(d => { setData(d); setLoading(false); })
            .catch(() => setLoading(false));
    }, [consultationId, token]);

    if (loading || !data) return null;

    const typeColor = (data.referralType || data.referral_type) === 'HOSPITAL'
        ? { bg: '#FFEBEE', border: '#FFCDD2', text: '#B71C1C', icon: '#C62828' }
        : { bg: '#E8EAF6', border: '#C5CAE9', text: '#1A237E', icon: '#283593' };

    return (
        <Box sx={{ mt: 1, p: 2, borderRadius: 2, bgcolor: typeColor.bg, border: `1px solid ${typeColor.border}` }}>
            <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
                <ScienceOutlined sx={{ fontSize: 16, color: typeColor.icon }} />
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.75rem', color: typeColor.text, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                    {data.referralType || data.referral_type} Referral · {data.priority}
                </Typography>
            </Stack>
            {data.destination && (
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.8rem', color: typeColor.text, fontWeight: 600 }}>
                    → {data.destination}
                </Typography>
            )}
            {data.reason && (
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.75rem', color: typeColor.text, opacity: 0.8, mt: 0.25 }}>
                    {data.reason}
                </Typography>
            )}
        </Box>
    );
}

/* ── Consultation Detail (from GET /api/consultations/{id}) ─ */
function ConsultationDetail({ consultationId, token }) {
    const [detail, setDetail]   = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        get(`/api/consultations/${consultationId}`, token)
            .then(d => { setDetail(d); setLoading(false); })
            .catch(() => setLoading(false));
    }, [consultationId, token]);

    if (loading) return (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 2 }}>
            <CircularProgress size={20} sx={{ color: '#8B7355' }} />
        </Box>
    );

    if (!detail) return null;

    const diagnoses = detail.diagnoses || [];
    const hasPrescription = detail.prescription || detail.prescriptionId;
    const hasReferral     = detail.referral     || detail.referralId;

    return (
        <Fade in>
            <Box>
                {/* Diagnoses */}
                {diagnoses.length > 0 && (
                    <Box sx={{ mb: 1.5 }}>
                        <Typography sx={{ fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.68rem', color: '#8B7355', mb: 1, letterSpacing: '0.08em', textTransform: 'uppercase' }}>
                            Diagnoses
                        </Typography>
                        <Stack spacing={0.5}>
                            {diagnoses.map((d, i) => (
                                <Stack key={i} direction="row" alignItems="center" justifyContent="space-between" sx={{ px: 1.5, py: 1, bgcolor: '#F5EFE6', borderRadius: 1.5 }}>
                                    <Stack direction="row" alignItems="center" spacing={1}>
                                        <FiberManualRecord sx={{ fontSize: 7, color: d.diagnosisType === 'CONFIRMED' ? '#4CAF50' : '#C4A882' }} />
                                        <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.83rem', fontWeight: 600, color: '#3D2B1F' }}>{d.diagnosisName}</Typography>
                                        {d.icdCode && <Chip label={d.icdCode} size="small" sx={{ height: 16, fontSize: '0.58rem', bgcolor: '#EDE5D8', color: '#6B4F35' }} />}
                                    </Stack>
                                    <Stack direction="row" alignItems="center" spacing={1}>
                                        <Chip label={d.diagnosisType?.replace('_', ' ')} size="small"
                                              sx={{ height: 18, fontSize: '0.6rem', fontFamily: 'Lato, sans-serif', fontWeight: 700,
                                                  bgcolor: d.diagnosisType === 'CONFIRMED' ? '#E8F5E9' : '#FFF3E0',
                                                  color:   d.diagnosisType === 'CONFIRMED' ? '#2E7D32' : '#E65100' }} />
                                        {d.confidenceScore && (
                                            <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.7rem', color: '#A89070', minWidth: 34, textAlign: 'right' }}>
                                                {d.confidenceScore}%
                                            </Typography>
                                        )}
                                    </Stack>
                                </Stack>
                            ))}
                        </Stack>
                    </Box>
                )}

                {/* Prescription from consultation endpoint */}
                <PrescriptionCard consultationId={consultationId} token={token} />

                {/* Referral from consultation endpoint */}
                <ReferralCard consultationId={consultationId} token={token} />

                {/* Notes */}
                {detail.notes && (
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.8rem', color: '#7A6352', mt: 1.5, fontStyle: 'italic' }}>
                        "{detail.notes}"
                    </Typography>
                )}
            </Box>
        </Fade>
    );
}

/* ── Consultation Card ───────────────────────────────────────*/
function ConsultationCard({ consultation }) {
    const { token } = useAuth();
    const [expanded, setExpanded] = useState(false);
    const c = consultation;

    const date = c.createdAt
        ? new Date(c.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
        : '—';

    const statusCfg  = STATUS[c.status] || {};
    const lineColor  = statusCfg.color || '#8B7355';
    const symptoms   = c.symptoms || c.consultationSymptoms || [];
    const diagnoses  = c.diagnoses || [];
    const primaryDx  = diagnoses.find(d => d.diagnosisType === 'CONFIRMED')
        || diagnoses.find(d => d.diagnosisType === 'AUTO_GENERATED')
        || diagnoses[0];

    return (
        <Box sx={{ display: 'flex', gap: 2, mb: 2, position: 'relative' }}>
            {/* Timeline spine */}
            <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: 36, flexShrink: 0 }}>
                <Box sx={{ width: 13, height: 13, borderRadius: '50%', bgcolor: lineColor, mt: '20px', flexShrink: 0, boxShadow: `0 0 0 3px ${lineColor}25`, transition: 'box-shadow 0.2s' }} />
                <Box sx={{ width: 2, bgcolor: `${lineColor}25`, flexGrow: 1, mt: '4px', minHeight: 20 }} />
            </Box>

            <Card elevation={0} sx={{ flexGrow: 1, bgcolor: '#FFFCF8', border: '1px solid #E8DDD0', borderRadius: 3, transition: 'box-shadow 0.2s', '&:hover': { boxShadow: '0 4px 20px rgba(139,115,85,0.1)', borderColor: '#C4A882' } }}>
                <CardActionArea onClick={() => setExpanded(p => !p)} sx={{ borderRadius: 3 }}>
                    <CardContent sx={{ py: 2, px: 2.5 }}>
                        <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
                            <Box>
                                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.68rem', color: '#A89070', mb: 0.4, letterSpacing: '0.05em', textTransform: 'uppercase' }}>
                                    {date}
                                </Typography>
                                <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.1rem', fontWeight: 600, color: '#3D2B1F' }}>
                                    {primaryDx ? primaryDx.diagnosisName : (c.notes || `Consultation #${c.id}`)}
                                </Typography>
                                {primaryDx?.icdCode && (
                                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.68rem', color: '#A89070' }}>ICD-10: {primaryDx.icdCode}</Typography>
                                )}
                            </Box>
                            <Stack direction="row" spacing={0.75} alignItems="center">
                                <StatusChip status={c.status} />
                                {c.complexityLevel && (
                                    <Chip label={COMPLEXITY[c.complexityLevel]?.label || c.complexityLevel} size="small"
                                          sx={{ height: 20, fontSize: '0.62rem', fontFamily: 'Lato, sans-serif', fontWeight: 700,
                                              bgcolor: COMPLEXITY[c.complexityLevel]?.bg || '#F5EFE6',
                                              color:   COMPLEXITY[c.complexityLevel]?.color || '#8B7355' }} />
                                )}
                                <IconButton size="small" sx={{ color: '#8B7355' }}>
                                    {expanded ? <ExpandLessOutlined fontSize="small" /> : <ExpandMoreOutlined fontSize="small" />}
                                </IconButton>
                            </Stack>
                        </Stack>

                        {symptoms.length > 0 && (
                            <Stack direction="row" spacing={0.75} sx={{ mt: 1.25, flexWrap: 'wrap', gap: 0.5 }}>
                                {symptoms.map((s, i) => (
                                    <Chip key={i} label={s.symptomName || s} size="small"
                                          sx={{ bgcolor: '#F2EAE0', color: '#6B4F35', fontFamily: 'Lato, sans-serif', fontSize: '0.68rem', fontWeight: 500, height: 20 }} />
                                ))}
                            </Stack>
                        )}
                    </CardContent>
                </CardActionArea>

                <Collapse in={expanded} timeout="auto">
                    <Divider sx={{ borderColor: '#E8DDD0' }} />
                    <CardContent sx={{ pt: 2, pb: 2.5, px: 2.5 }}>
                        <ConsultationDetail consultationId={c.id} token={token} />
                    </CardContent>
                </Collapse>
            </Card>
        </Box>
    );
}

/* ── Main Page ───────────────────────────────────────────────*/
export default function ConsultationsPage() {
    const { token } = useAuth();
    const navigate  = useNavigate();

    const [consultations, setConsultations] = useState([]);
    const [loading, setLoading]             = useState(true);
    const [error, setError]                 = useState('');
    const [tab, setTab]                     = useState(0);

    useEffect(() => {
        get('/api/consultations/my', token)
            .then(d => { setConsultations(Array.isArray(d) ? d : []); setLoading(false); })
            .catch(() => { setError('Could not load consultations.'); setLoading(false); });
    }, [token]);

    const filtered = consultations.filter(c => {
        if (tab === 0) return true;
        if (tab === 1) return c.status === 'COMPLETED';
        if (tab === 2) return ['SCHEDULED','IN_PROGRESS','FORM_GENERATED','FORM_COMPLETED','DIAGNOSIS_PENDING','PENDING_FORM'].includes(c.status);
        if (tab === 3) return ['CANCELLED','EMERGENCY_REDIRECT'].includes(c.status);
        return true;
    });
    const sorted = [...filtered].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

    return (
        <Box sx={{ p: { xs: 2, md: 4 }, maxWidth: 860, mx: 'auto' }}>

            <Stack direction="row" justifyContent="space-between" alignItems="flex-end" sx={{ mb: 4 }}>
                <Box>
                    <IconButton onClick={() => navigate('/dashboard')} sx={{ mb: 0.5, color: '#8B7355', '&:hover': { bgcolor: '#F2EAE0' } }}>
                        <ArrowBackOutlined />
                    </IconButton>
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.72rem', color: '#A89070', letterSpacing: '0.12em', textTransform: 'uppercase', mb: 0.5 }}>
                        Medical Records
                    </Typography>
                    <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: { xs: '2rem', md: '2.5rem' }, fontWeight: 700, color: '#3D2B1F', lineHeight: 1.1 }}>
                        My Consultations
                    </Typography>
                </Box>
                <Button variant="contained" startIcon={<AddOutlined />} onClick={() => navigate('/consultations/new')}
                        sx={{ bgcolor: '#8B7355', color: '#fff', borderRadius: 3, fontFamily: 'Lato, sans-serif', fontWeight: 600, textTransform: 'none', px: 2.5, py: 1, '&:hover': { bgcolor: '#6D5840' } }}>
                    New Consultation
                </Button>
            </Stack>

            <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 3,
                '& .MuiTab-root': { fontFamily: 'Lato, sans-serif', fontSize: '0.82rem', fontWeight: 600, textTransform: 'none', color: '#A89070', minWidth: 'auto', px: 2 },
                '& .Mui-selected': { color: '#8B7355 !important' },
                '& .MuiTabs-indicator': { bgcolor: '#8B7355' } }}>
                {ALL_TABS.map(t => <Tab key={t} label={t} />)}
            </Tabs>

            {loading ? (
                <Box sx={{ display: 'flex', justifyContent: 'center', pt: 8 }}><CircularProgress sx={{ color: '#8B7355' }} /></Box>
            ) : error ? (
                <Alert severity="error" sx={{ borderRadius: 2 }}>{error}</Alert>
            ) : sorted.length === 0 ? (
                <Box sx={{ textAlign: 'center', py: 10 }}>
                    <MonitorHeartOutlined sx={{ fontSize: 56, color: '#D4C4B0', mb: 2 }} />
                    <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.4rem', color: '#A89070' }}>No consultations found</Typography>
                    <Button variant="outlined" onClick={() => navigate('/consultations/new')}
                            sx={{ mt: 3, borderColor: '#8B7355', color: '#8B7355', borderRadius: 3, fontFamily: 'Lato, sans-serif', textTransform: 'none', fontWeight: 600 }}>
                        Start Consultation
                    </Button>
                </Box>
            ) : (
                <Box>
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.75rem', color: '#A89070', mb: 2 }}>
                        {sorted.length} {sorted.length === 1 ? 'record' : 'records'} · click to expand
                    </Typography>
                    {sorted.map(c => <ConsultationCard key={c.id} consultation={c} />)}
                </Box>
            )}
        </Box>
    );
}