import { useEffect, useState } from 'react';
import {
    Box, Typography, Chip, Card, CardContent, Stack, Divider,
    CircularProgress, Alert, Collapse, IconButton,
} from '@mui/material';
import {
    MedicalServicesOutlined, AutoAwesomeOutlined, ArrowBackOutlined,
    VerifiedUserOutlined, ExpandMoreOutlined, ExpandLessOutlined,
    AccessTimeOutlined, CheckCircleOutlined, ErrorOutlined,
} from '@mui/icons-material';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { getMyPrescriptions } from '../api/prescriptions';

const PRESC_STATUS = {
    ACTIVE:   { label: 'Active',   color: '#2E7D32', bg: '#E8F5E9', Icon: CheckCircleOutlined },
    EXPIRED:  { label: 'Expired',  color: '#795548', bg: '#EFEBE9', Icon: AccessTimeOutlined },
    REVOKED:  { label: 'Revoked',  color: '#B71C1C', bg: '#FFEBEE', Icon: ErrorOutlined },
};

function MedicationRow({ med }) {
    return (
        <Box
            sx={{
                display: 'grid',
                gridTemplateColumns: '1fr auto',
                gap: 1,
                py: 1.25,
                px: 2,
                borderRadius: 2,
                bgcolor: '#F9F5F0',
                border: '1px solid #E8DDD0',
            }}
        >
            <Box>
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.88rem', color: '#3D2B1F' }}>
                    {med.medicationName || med.medication_name}
                </Typography>
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.78rem', color: '#7A6352', mt: 0.25 }}>
                    {med.dosage} · {med.frequency}
                    {med.durationDays || med.duration_days
                        ? ` · ${med.durationDays || med.duration_days} days`
                        : ''}
                </Typography>
                {(med.instructions) && (
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.72rem', color: '#A89070', mt: 0.5, fontStyle: 'italic' }}>
                        {med.instructions}
                    </Typography>
                )}
            </Box>
        </Box>
    );
}

function PrescriptionCard({ prescription: p }) {
    const [expanded, setExpanded] = useState(false);

    const statusCfg = PRESC_STATUS[p.status] || PRESC_STATUS.ACTIVE;
    const isAuto = p.isAutoGenerated ?? p.is_auto_generated;
    const meds = p.medications || p.prescriptionMedications || p.prescription_medications || [];

    const issuedAt = p.issuedAt || p.issued_at;
    const validUntil = p.validUntil || p.valid_until;

    const issuedLabel = issuedAt
        ? new Date(issuedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
        : '—';
    const validLabel = validUntil
        ? new Date(validUntil).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
        : null;

    const isExpired = validUntil && new Date(validUntil) < new Date();

    return (
        <Card
            elevation={0}
            sx={{
                bgcolor: '#FFFCF8',
                border: `1px solid #E8DDD0`,
                borderRadius: 3,
                mb: 2,
                transition: 'box-shadow 0.2s',
                '&:hover': { boxShadow: '0 4px 20px rgba(139,115,85,0.1)' },
            }}
        >
            {/* Header */}
            <CardContent
                sx={{ pb: 2, px: 3, cursor: 'pointer' }}
                onClick={() => setExpanded((v) => !v)}
            >
                <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
                    <Box sx={{ flexGrow: 1 }}>
                        <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.75 }}>
                            <MedicalServicesOutlined sx={{ fontSize: 18, color: '#8B7355' }} />
                            <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.15rem', fontWeight: 700, color: '#3D2B1F' }}>
                                Prescription #{p.id}
                            </Typography>
                            {isAuto && (
                                <Chip
                                    icon={<AutoAwesomeOutlined sx={{ fontSize: '12px !important' }} />}
                                    label="Auto-generated"
                                    size="small"
                                    sx={{ height: 20, fontSize: '0.63rem', bgcolor: '#E8EAF6', color: '#3949AB', fontFamily: 'Lato, sans-serif', fontWeight: 700, border: '1px solid #C5CAE9' }}
                                />
                            )}
                            {!isAuto && (
                                <Chip
                                    icon={<VerifiedUserOutlined sx={{ fontSize: '12px !important' }} />}
                                    label="Doctor issued"
                                    size="small"
                                    sx={{ height: 20, fontSize: '0.63rem', bgcolor: '#E8F5E9', color: '#2E7D32', fontFamily: 'Lato, sans-serif', fontWeight: 700, border: '1px solid #C8E6C9' }}
                                />
                            )}
                        </Stack>

                        <Stack direction="row" spacing={2} sx={{ pl: 0.5 }}>
                            <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.78rem', color: '#A89070' }}>
                                Issued: <strong style={{ color: '#6B4F35' }}>{issuedLabel}</strong>
                            </Typography>
                            {validLabel && (
                                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.78rem', color: isExpired ? '#B71C1C' : '#A89070' }}>
                                    Valid until: <strong style={{ color: isExpired ? '#B71C1C' : '#6B4F35' }}>{validLabel}</strong>
                                </Typography>
                            )}
                        </Stack>
                    </Box>

                    <Stack direction="row" alignItems="center" spacing={1}>
                        <Chip
                            icon={<statusCfg.Icon sx={{ fontSize: '13px !important', color: `${statusCfg.color} !important` }} />}
                            label={isExpired && p.status !== 'REVOKED' ? 'Expired' : statusCfg.label}
                            size="small"
                            sx={{ bgcolor: isExpired ? '#EFEBE9' : statusCfg.bg, color: isExpired ? '#795548' : statusCfg.color, fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.7rem', border: `1px solid ${statusCfg.color}25` }}
                        />
                        {expanded ? (
                            <ExpandLessOutlined sx={{ color: '#8B7355', fontSize: 20 }} />
                        ) : (
                            <ExpandMoreOutlined sx={{ color: '#8B7355', fontSize: 20 }} />
                        )}
                    </Stack>
                </Stack>

                {/* Medications preview when collapsed */}
                {!expanded && meds.length > 0 && (
                    <Stack direction="row" spacing={0.75} sx={{ mt: 1.25, flexWrap: 'wrap', gap: 0.75 }}>
                        {meds.map((m, i) => (
                            <Chip
                                key={i}
                                label={m.medicationName || m.medication_name}
                                size="small"
                                sx={{ bgcolor: '#F2EAE0', color: '#6B4F35', fontFamily: 'Lato, sans-serif', fontSize: '0.72rem', fontWeight: 500, height: 22 }}
                            />
                        ))}
                    </Stack>
                )}
            </CardContent>

            {/* Expanded medications */}
            <Collapse in={expanded} timeout="auto">
                <Divider sx={{ borderColor: '#E8DDD0', mx: 3 }} />
                <CardContent sx={{ pt: 2, pb: 2.5, px: 3 }}>
                    {meds.length > 0 ? (
                        <>
                            <Typography sx={{ fontFamily: 'Lato, sans-serif', fontWeight: 700, fontSize: '0.72rem', color: '#8B7355', mb: 1.5, letterSpacing: '0.08em', textTransform: 'uppercase' }}>
                                Medications ({meds.length})
                            </Typography>
                            <Stack spacing={1}>
                                {meds.map((m, i) => (
                                    <MedicationRow key={i} med={m} />
                                ))}
                            </Stack>
                        </>
                    ) : (
                        <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.82rem', color: '#A89070', fontStyle: 'italic' }}>
                            No medication details available.
                        </Typography>
                    )}
                </CardContent>
            </Collapse>
        </Card>
    );
}

/* ─── Main Page ──────────────────────────────────────────── */
export default function PrescriptionsPage() {
    const { token } = useAuth();
    const navigate = useNavigate();
    const [prescriptions, setPrescriptions] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        getMyPrescriptions(token)
            .then((data) => {
                setPrescriptions(Array.isArray(data) ? data : []);
                setLoading(false);
            })
            .catch(() => {
                setError('Could not load prescriptions.');
                setLoading(false);
            });
    }, [token]);

    const active = prescriptions.filter(
        (p) => p.status === 'ACTIVE' && (!p.validUntil || new Date(p.validUntil) >= new Date())
    );
    const past = prescriptions.filter(
        (p) => p.status !== 'ACTIVE' || (p.validUntil && new Date(p.validUntil) < new Date())
    );

    return (
        <Box sx={{ p: { xs: 2, md: 4 }, maxWidth: 860, mx: 'auto' }}>
            <IconButton onClick={() => navigate('/dashboard')} sx={{ mb: 2, color: '#8B7355', '&:hover': { bgcolor: '#F2EAE0' } }}>
                <ArrowBackOutlined />
            </IconButton>
            <Box sx={{ mb: 4 }}>
                <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.75rem', color: '#A89070', letterSpacing: '0.12em', textTransform: 'uppercase', mb: 0.5 }}>
                    Medical Records
                </Typography>
                <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: { xs: '2rem', md: '2.5rem' }, fontWeight: 700, color: '#3D2B1F', lineHeight: 1.1 }}>
                    My Prescriptions
                </Typography>
            </Box>

            {loading ? (
                <Box sx={{ display: 'flex', justifyContent: 'center', pt: 8 }}>
                    <CircularProgress sx={{ color: '#8B7355' }} />
                </Box>
            ) : error ? (
                <Alert severity="error" sx={{ borderRadius: 2 }}>{error}</Alert>
            ) : prescriptions.length === 0 ? (
                <Box sx={{ textAlign: 'center', py: 10 }}>
                    <MedicalServicesOutlined sx={{ fontSize: 56, color: '#D4C4B0', mb: 2 }} />
                    <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.4rem', color: '#A89070' }}>
                        No prescriptions yet
                    </Typography>
                    <Typography sx={{ fontFamily: 'Lato, sans-serif', fontSize: '0.85rem', color: '#C4A882', mt: 1 }}>
                        Prescriptions issued after consultations will appear here.
                    </Typography>
                </Box>
            ) : (
                <>
                    {active.length > 0 && (
                        <Box sx={{ mb: 4 }}>
                            <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.25rem', fontWeight: 600, color: '#3D2B1F', mb: 2 }}>
                                Active ({active.length})
                            </Typography>
                            {active.map((p) => <PrescriptionCard key={p.id} prescription={p} />)}
                        </Box>
                    )}
                    {past.length > 0 && (
                        <Box>
                            <Typography sx={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '1.25rem', fontWeight: 600, color: '#3D2B1F', mb: 2 }}>
                                Past ({past.length})
                            </Typography>
                            {past.map((p) => <PrescriptionCard key={p.id} prescription={p} />)}
                        </Box>
                    )}
                </>
            )}
        </Box>
    );
}